# Generated by Django 3.2.16 on 2022-11-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(default='22233344455', max_length=15),
        ),
    ]
