# Generated by Django 3.2.16 on 2022-11-16 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
