# Generated by Django 3.2.16 on 2022-11-09 15:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2348131234568', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
