# Generated by Django 3.2.16 on 2022-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Lagos', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
