# Generated by Django 3.2.16 on 2022-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0003_brand_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='name', max_length=50, unique=True),
        ),
    ]
