# Generated by Django 3.2.16 on 2022-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
