# Generated by Django 3.2.16 on 2022-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0003_brand_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
