# Generated by Django 3.2.16 on 2022-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0004_auto_20221109_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nin',
            field=models.CharField(default='222333444555', max_length=30),
        ),
    ]
