# Generated by Django 3.2.16 on 2022-11-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0005_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(default='scotch', max_length=50, unique=True),
        ),
    ]
