# Generated by Django 3.2.16 on 2022-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0007_remove_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(default='scotch', max_length=100),
        ),
    ]
