# Generated by Django 3.2.16 on 2022-11-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0008_alter_order_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
    ]
