# Generated by Django 3.2.16 on 2022-11-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0009_remove_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(default='scotch', max_length=500),
        ),
    ]
